### ISSUE TITLE
Warning user_ldap not suitable default quota

### ISSUE THREAD

**Issue by IRAM38** [owncloud/user_ldap#111]
hello Everybody!
I have the same issue, I don't understand. I have Cloud Vers9.1.5 (stable)

Warning user_ldap not suitable default quota found for user xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

And the user Quota (for exemple 50Gb) is set automatically to Default quota (4Gb) ..

Thanks for your help.

**Comment by cristiy2007** [comment]
Hello,

I have the exact same problem, I set the quota at 50 GB, and after 1 days aprox, it gets set to the default quota for 1 GB. I have Owncloud 9.1.5.
I will be updating today to 9.1.6 but I don't see anuthing related to this issue in the changelog so I don't expect it will be fixed.
Users quota is only defined in Owncloud, nothing from ldap.

Thanks

**Comment by PVince81** [comment]
please first upgrade to 9.1.6, see changelog item:

"[major] Default quota display in users page now works correctly again - https://github.com/owncloud/core/issues/27896"

If the problem persists then it could be https://github.com/owncloud/core/issues/28380

**Comment by nfc036** [comment]
We observed this issue as well and from my investigation it is a problem of user_ldap. [Here](https://github.com/owncloud/user_ldap/blob/master/lib/User/User.php#L553) the module is setting the quota to default if there are no relevant Attributes in LDAP. The function should take into account the already existing entries. Changing the given line to `$targetUser->setQuota($targetUser->getQuota())` should keep the existing entry or set a new entry 'default' ('default' is the standard return value of getQuota).

**Comment by nfc036** [comment]
pull request #122 created.

**Comment by cristiy2007** [comment]
Hello,

Please note that I completed the update to Owncloud 9.1.6 and I am still having the same issue. It happens random, take s betwen 24-48 hours and it affects random users, when it does I see this message in the logs:
```"...app":"user_ldap","message":"not suitable default quota found for user user1: []","level":2,"time":"2017-08-21T05:09:58+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"user2"}
"```

and it actually seems to happen when someonelse is trying to access/modify a share file or folder, so when user2 is accessing files/folders shared from user1 it gives the error "not suitable quota found for user user1" and resets his quota.

We're using this for 500 users so it's hard to keep track every morning to check which quota got changed to the default instead of the used configured.
