### ISSUE TITLE
Some of the users are unknown for ldap:update-group

### ISSUE THREAD

**Issue by PVince81** [owncloud/user_ldap#20]
When running "ldap:update-group" with unknown group names, it fails with:
"Some of the groups are unknown"

It doesn't tell which and also doesn't process any other groups.

So far the only way to use this command is to pass a list of groups explicitly.
Let's say an admin prepares a text file with a list of all groups to sync and passes it to the command, maybe they do it in a cron job.So far so good.

As soon as a LDAP admin deletes a group, the command will work once and find that the group must be deleted locally as well. Still good so far.

But then subsequent runs will fail and none of the other groups will sync until the admin adjusts the text file to remove the missing group.

To avoid such confusion and frustration, I suggest to modify as follows:

1. Process all known groups and skip the unknown ones
2. At the end of the summary, display a list of groups that were not found on LDAP.

Related to https://github.com/owncloud/user_ldap/pull/14

@jvillafanez @felixboehm

**Comment by jvillafanez** [comment]
I guess the main change will be in the `checkGroupMappingExists` function: instead of just returning `true`or `false`, we'll return a double list with the existing and non-existing groups. We can just show the missing groups and process the rest easily.

There won't be a summary at the end, but at the beginning because it's the most straightforward solution with the given code.

Any expectations with the amount of groups to be processed by this command? If we expect a lot of groups we might need some minor optimizations since we'll need to check what groups are present in an array. If there are few, we can just do a simple check ignoring any optimization.

**Comment by PVince81** [comment]
> Any expectations with the amount of groups to be processed by this command? If we expect a lot of groups we might need some minor optimizations since we'll need to check what groups are present in an array. If there are few, we can just do a simple check ignoring any optimization.

@felixboehm @butonic
