### ISSUE TITLE
Reduce elapsed time for CI

### ISSUE THREAD

**Issue by phil-davis** [owncloud/user_ldap#422]
CI is taking an elapsed time of about 2 hours.

- [x] see which CI jobs/suites are taking a long time
- [x] split them

And then:
- [x] make tests more efficient/faster (if there are "obvious" test code changes that can make things faster)

**Comment by paurakhsharma** [comment]
Here are the suite name with their respective run time on drone:

- apiProvisioningLDAP        - 35min
- apiUserLDAP                    -  22min
- apiUserLDAPConnection  - 19min
- apiUserLDAPSharing        - 8min  
- cliProvisioning                   - 13min 
- webUIProvisioning            - 28min 
- webUIUserLDAP               - 28min

Since the longest running suite from `user_ldap` is 35min splitting it doesn't have too much to gain.

After this issues was created there was CI speed up here https://github.com/owncloud/QA/issues/621
which has reduced the CI time in `user_ldap` to about 1hr 15min in average.

So, I don't think suite split is required here.
What do you think @phil-davis

**Comment by phil-davis** [comment]
The jobs that take a long time are:
https://drone.owncloud.com/owncloud/user_ldap/1625

- 67 core-web-acceptance - 53 min
- 78 apiShareManagement  - 71 min
- 79 apiShareManagementBasic - 81 min
- 80 apiShareOperations - 50 min
- 87 apiWebdavMove - 45 min

Those are core suites. The `apiShare` ones already are getting slow in core, because we have been adding test scenarios recently. I will look at splitting those in core while I am adding more scenarios.

`core-web-acceptance` could be made into 2 parts.
@paurakhsharma see if it easily can have `DIVIDE_INTO_NUM_PARTS=2` and jobs with `RUN_PART=` `RUN_PART=2` like we do with encryption.

Those things should get the longest job down to 45 or 50 minutes.

**Comment by phil-davis** [comment]
The `apiShare*` suites from core are the ones taking the longest to run (60 to 90 minutes).
Those also take a long time in core. So it would be useful to sort them out in core anyway.

The core webUI tests are running in 2 parts. But the first part has only 8 scenarios and the second part has 42 scenarios. That should be balanced better.

**Comment by phil-davis** [comment]
ToDo:
- [ ] split the `apiShare*` suites in core into smaller (and still logical pieces)

That will help the core run time, as well as the run time here in user_ldap

**Comment by phil-davis** [comment]
Added to sprint for this week. It needs to happen after we merge the user-group-share-expiry-date stuff, because that adds/modifies lots of scenarios in these test suites.

**Comment by phil-davis** [comment]
A current example of long run times for test suites is https://drone.owncloud.com/owncloud/core/22170
00:30:41 - apiShareManagement 
01:25:10 - apiShareManagementBasic - too long
00:43:37 - apiShareOperations
01:33:10 - apiShareReshare - too long
00:21:34 - apiShareUpdate

**Comment by phil-davis** [comment]
Done in https://github.com/owncloud/core/pull/36629 and #492
