### ISSUE TITLE
LDAP Cache

### ISSUE THREAD

**Issue by patrikx3** [owncloud/user_ldap#60]
I have Cache Time-To-Live to 600 seconds (is that right config?), still when I refresh or download 100+ files, it hits a new request it uses a new  LDAP request.
How can I cache or keep it in the session instead of authorize LDAP every reload/refresh or anything?
Right now my CPU usage is too high for this.
(Samba is also slow, but *cloud could use the session isnit?)

**Comment by PVince81** [comment]
Did you enable memcache ? That should reduce the requests a bit but not completely.

**Comment by patrikx3** [comment]
What do you mean? 
Doesn't the session keep the auth? 
Why does it generate a new Auth for every request? Why do I need a memcache for a simple session? 
The session knows the used login, name, etc, so that it doesn't create a new request.
This way I can use a plain Http Basic Auth and it is the same. 

The session is to keep instead of hitting the backend every request.

I add in memcache and it is still not working with the session kept?
Weird!
Thanks!

**Comment by PVince81** [comment]
@jvillafanez

**Comment by jvillafanez** [comment]
I think there are some misunderstandings about how the LDAP app is working.
* Each request will use fresh resources, in particular LDAP connections. Each request will use a new LDAP connection that will need to be authenticated and will requests data to the LDAP server. ownCloud can't do anything about this. I think it's apache the one that spawns a new php process to handle that request, so as said, ownCloud can't do anything.
* ownCloud can cache data from the LDAP server, and use that data during next requests instead of connecting to the LDAP server. This is different than reusing LDAP connections.

    In order to enable caching, you need to set up either redis or memcached to be used by ownCloud as memory cache. Once it's properly set and configured (including some changes required in the ownCloud's config.php file), the LDAP app should start to use it and reduce the number of requests to the LDAP server. (There is documentation about how to setup redis / memcached in ownCloud)

* The cache time-to-live is used when caching is enabled. After the ttl expires, the data cached will be removed from the cache and new requests will be done to the LDAP server to fetch fresh data.

A couple of notes:
* If there isn't any cache active, the LDAP app will connect to the LDAP as requested.
* Each request will use a fresh connection to the LDAP if needed. This means:
    * Different requests will need to be authenticated, even if they're using the same credentials
    * The connection is made directly to the LDAP server. The LDAP app isn't connecting to a proxy or any other service that could be in between ownCloud and the LDAP server to handle the connections.

**Comment by patrikx3** [comment]
this is weird why you need redis/memcache, you just not use simple php session ?
