### ISSUE TITLE
Missing user count for local groups

### ISSUE THREAD

**Issue by phil-davis** [owncloud/user_ldap#717]
core PR https://github.com/owncloud/core/pull/39721 changed the behavior of the groups on the user management page. If the group is an LDAP group, or for whatever reason the group member count is zero or not available, then the count is not displayed at all.

But in https://github.com/owncloud/user_ldap/blob/master/tests/acceptance/features/webUIProvisioning/groups.feature
```
Scenario: Adding database user to database group should be possible
    Given user "db-user" has been created with default attributes in the database user backend
    And group "db-group" has been created in the database user backend
    And the administrator has browsed to the users page
    When the administrator adds user "db-user" to group "db-group" using the webUI
    Then user "db-user" should exist
    And user "db-user" should belong to group "db-group"
    And the user count of group "db-group" should not be displayed on the webUI
    # for a database group and user, we should really see the user in the count
    #And the user count of group "db-group" should display 1 users on the webUI
```

"The system" is running with an LDAP backend. But local users and groups can also be added.

In this scenario, a local user and group are created. The local user is added to the local group. The group member count is not displayed. I think that it should display a member count of "1".

**Comment by phil-davis** [comment]
The test scenarios were added for issue #716 to cover behavior changes in core PR https://github.com/owncloud/core/pull/39721

@jvillafanez @JanAckermann is the scenario above a bug or a feature?

**Comment by jvillafanez** [comment]
Technically, the user count isn't displayed when the group list isn't sorted by user count. This happens when LDAP is involved.

According to a code comment, there is a performance problem with the user count and LDAP, likely caused by a great number of queries we might need in order to get the user count for those groups. This means that it's unlikely that we can get the user count effectively. In this scenario, if we add a local group, it's better if we don't show the user count in order to keep consistency with the rest of the groups.

**Comment by phil-davis** [comment]
OK then it's a feature. I am happy with that. And I think that other users who have an LDAP backend will not often be interested in having the member-count of local groups displayed. Mostly they may not even have local groups - both groups and users will usually come from LDAP for those installations.
