### ISSUE TITLE
[10.0.0] Show disable users -- ldap:check-user??

### ISSUE THREAD

**Issue by cdamken** [owncloud/user_ldap#97]
#occ commands:
```
ldap:show-config
ldap:set-config
ldap:test-config
ldap:create-empty-config
ldap:delete-config
ldap:search
ldap:check-user
ldap:update-group
```
```
user:add
user:delete
user:disable
user:enable
user:lastseen
user:report
user:resetpassword
user:setting
user:sync
```

How can I check the disables users? 

Does `ldap:check-user` has this function? Does it check it `oc_ldap_user_mapping` or in `oc_accounts` or in the LDAP server with the `login filters`?

@jvillafanez @tomneedham @felixboehm @butonic

**Comment by cdamken** [comment]
Now there is a new behavior with `occ user:sync`:

```
sudo -u www-data php occ user:sync "OCA\User_LDAP\User_Proxy"
If unknown users are found, what do you want to do with their accounts? (removing the account will also remove its data)
  [0] disable
  [1] remove
  [2] ask later
 > 
```

How can I see the disabled users?

If I select ask later, where can I change?

**Comment by jvillafanez** [comment]
The "ask later" option is to know what user aren't known before disabling or removing. This might be useful if you expect a few users to appear before removing their accounts, so instead of blindly remove whatever accounts are detected you can check if the action will be applied to the accounts you expect.

The list of disabled users must be managed by core, because it's core the one which knows the account status.

**Comment by jvillafanez** [comment]
As said, what is disabled is the account, not the user. LDAP doesn't know anything about the ownCloud accounts nor its status, so it isn't responsible for this.
Opened https://github.com/owncloud/core/issues/28056 because it's core's responsability to provide that information.

**Comment by Manueldona** [comment]
I don't know way, all my users from the LDAP give me an user disabled when I login.
What can I do?

**Comment by butonic** [comment]
@Manueldona open a new issue with a more detailed error report?
